version: '3'
services:
  backend:
    build: .
    environment:
      - FILE_INPUT=files_input
      - FILE_OUTPUT=files_output
    volumes:
      - demo_2_files_input:/app/files_input
      - demo_2_files_output:/app/files_output
    # command: ["ls"]

volumes:  # Volumes for persisting data
  demo_2_files_input:
    driver: local
  demo_2_files_output:
    driver: local
